apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: labhome
    hostPath:
      path: /labhome
      type: Directory
      readOnly: false
  - name: auto
    hostPath:
      path: /auto
      type: Directory
      readOnly: false
  containers:
  - name: jnlp
    image: harbor.mellanox.com/toolbox/c3po-jnlp:latest
    workingDir: /tmp
    # securityContext:
    #   runAsUser: 7331
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "4"
    volumeMounts:
    - mountPath: /auto
      name: auto
      mountPropagation: HostToContainer
    - mountPath: /labhome
      name: labhome
      mountPropagation: HostToContainer
  - name: dind
    image: harbor.mellanox.com/toolbox/devops-tools-build:0.0.7
    imagePullPolicy: Always
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "4"
    tty: true
    command: ["cat"]
    # securityContext:
    #   runAsUser: 7331
    volumeMounts:
    - name: labhome
      mountPath: /labhome
      mountPropagation: HostToContainer
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "8Gi"
        cpu: "4"
    tty: true
    command:
    - sleep
    args:
    - 9000
    volumeMounts:
    - mountPath: /labhome
      name: labhome
      mountPropagation: HostToContainer
    - mountPath: /auto
      name: auto
      mountPropagation: HostToContainer
