apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: harbor.mellanox.com/toolbox/c3po-jnlp:latest
    workingDir: /tmp
    securityContext:
      runAsUser: 7331  # TODO: recall which user this is
    resources:
      requests:
        memory: "4Gi"  # TODO: try to decrease
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "4"
    volumeMounts:
    - mountPath: /auto
      name: auto
      mountPropagation: HostToContainer
    - mountPath: /labhome
      name: labhome
      mountPropagation: HostToContainer

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    resources:
      requests:
        memory: "8Gi"  # TODO: try to decrease
        cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "4"
    tty: true
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - mountPath: /labhome
      name: labhome
      mountPropagation: HostToContainer
    - mountPath: /auto
      name: auto
      mountPropagation: HostToContainer

  volumes:
  - name: labhome
    hostPath:
      path: /labhome
      type: Directory
      readOnly: false
  - name: auto
    hostPath:
      path: /auto
      type: Directory
      readOnly: false
