# TODO: when done remove ~/projects/jenkins-confs/jenkins-files/network-operator/ocp-bundle-push.jenkinsfile
name: Package OCP Bundle

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"  # TODO: safe to remove wild card from end of pattern?
    branches:
    - "feature/ocp-bundle"  # TODO: remove before merging

jobs:
  ocp-package:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: feature/ocp-bundle # master  # TODO: revert to 'master' when done
      REGISTRY: nvcr.io/nvstaging/mellanox  # TODO: noam angel approved to change to nvstaging; requested we PoC it
      IMAGE_NAME: network-operator
      BUNDLE_IMAGE_NAME: network-operator-bundle
    steps:
    - uses: actions/checkout@v4
    - if: github.ref_name == env.DEFAULT_BRANCH  # TODO: remove this option entirely (we only need tag trigger), after developing
      run: |
        echo VERSION_WITH_PREFIX=v99.9.9-beta.9   >> $GITHUB_ENV  # mock version - to be used only for internal testing!
        echo VERSION_WITHOUT_PREFIX=99.9.9-beta.9 >> $GITHUB_ENV  # mock version - to be used only for internal testing!
    - if: github.ref_type == 'tag'
      name: Determine docker tag (when git tag)
      run: |
        git_tag=${{ github.ref_name }}
        echo VERSION_WITH_PREFIX=$git_tag        >> $GITHUB_ENV
        echo VERSION_WITHOUT_PREFIX=${git_tag:1} >> $GITHUB_ENV  # without the 'v' prefix
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Make bundle
      env:
        DEFAULT_CHANNEL: stable
        CHANNELS: stable,${{ env.VERSION_WITH_PREFIX }}
        TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}
        BUNDLE_IMG: ${{ env.REGISTRY }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}-mzeevi-test-deleteme  # TODO: remove test suffix, after developing
        VERSION: ${{ env.VERSION_WITHOUT_PREFIX }}
        NGC_CLI_API_KEY: ${{ secrets.NVCR_TOKEN }}
      run: |
        echo "Bundle full tag will be: $BUNDLE_IMG"
        make image release-build bundle bundle-build # bundle-push  # TODO: only push when build result is satisfying
        echo AAAA
        make bundle-push                                          # TODO: only push when build result is satisfying
        echo AAAA
        # TODO: automate PR creation to redhat openshift certified operators
