# TODO: when done remove ~/projects/jenkins-confs/jenkins-files/network-operator/ocp-bundle-push.jenkinsfile
name: Package OCP Bundle

on:
  push:
    branches:
    - "feature/ocp-bundle"  # TODO: remove before merging
    - "master"
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"  # TODO: safe to remove wild card from end of pattern?

jobs:
  ocp-package:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: feature/ocp-bundle # master  # TODO: revert to 'master' when done
      REGISTRY: nvcr.io/nvstaging/mellanox
      IMAGE_NAME: network-operator
      # BUNDLE_REGISTRY: harbor.mellanox.com/cloud-orchestration-dev  # noam angel approved to change to nvstaging; requested we PoC it
      BUNDLE_IMAGE_NAME: network-operator-bundle
    steps:
    - uses: actions/checkout@v4
    - if: github.ref_name == env.DEFAULT_BRANCH
      name: Determine docker tag (when git branch)
      run: |
        echo VERSION_WITH_PREFIX=latest           >> $GITHUB_ENV
        echo VERSION_WITHOUT_PREFIX=latest >> $GITHUB_ENV
    - if: github.ref_type == 'tag'
      name: Determine docker tag (when git tag)
      run: |
        version=${{ github.ref_name }}
        echo VERSION_WITH_PREFIX=$version               >> $GITHUB_ENV
        echo VERSION_WITHOUT_PREFIX=${version:1} >> $GITHUB_ENV  # without the 'v' prefix
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Make bundle
      env:
        TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}
        BUNDLE_IMG: ${{ env.REGISTRY }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}
        DEFAULT_CHANNEL: stable
        CHANNELS: stable,${{ env.VERSION_WITH_PREFIX }}
        VERSION: ${{ env.VERSION_WITHOUT_PREFIX }}
      run: |
        which go      # TODO: checking for something else...
        echo "Bundle tag will be: $BUNDLE_IMG"
        # make image release-build bundle bundle-build # bundle-push  # TODO: only push when build result is satisfying
        # TODO: fine-grain separate make targets, to see which fails
        echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        make image
        echo BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        make release-build
        echo CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        make bundle
        echo DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
        make bundle-build
