# migrated from: ~/projects/jenkins-confs/jenkins-files/network-operator/ocp-bundle-push.jenkinsfile
name: Package OCP Bundle

on:
  push:
    branches:
    - "feature/ocp-bundle"  # TODO: remove before merging
    - "master"
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"  # TODO: set `version` from tag and `tag` without the prefix "v"  # TODO: safe to remove wild card from end of pattern?

jobs:
  ocp-package:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: master
      REGISTRY: nvcr.io/nvstaging/mellanox
      IMAGE_NAME: network-operator
      BUNDLE_REGISTRY: harbor.mellanox.com/cloud-orchestration-dev  # noam angel approved to change to nvstaging; but we should PoC
      BUNDLE_IMAGE_NAME: ${{ env.IMAGE_NAME }}-bundle
    steps:
    - uses: actions/checkout@v4
    - if: github.ref_name == env.DEFAULT_BRANCH
      name: Determine docker tag (when git branch)
      run: |
        echo APP_VERSION=""latest"" >> $GITHUB_ENV  # TODO: test if double quotes required
        echo VERSION=latest         >> $GITHUB_ENV
    - if: github.ref_type == 'tag'
      name: Determine docker tag (when git tag)
      run: |
        version=${{ github.ref_name }}
        tag=${version:1}  # without the 'v' prefix
        echo APP_VERSION=""$app_version"" >> $GITHUB_ENV
        echo VERSION=""$chart_version""   >> $GITHUB_ENV
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Make bundle
      env:
        TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}  # TODO: validate env var substituion successful
        BUNDLE_IMG: ${{ env.BUNDLE_REGISTRY }/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.VERSION }}
        DEFAULT_CHANNEL: stable
        CHANNELS: stable,${{ env.VERSION }}
        VERSION: ${tag}                            # TODO: ammend
        TAG: ${REGISTRY}/${IMAGE_NAME}:${version}  # TODO: ammend
      run: |
        env  # TODO: validate all above env vars are properly created with their full values
        which jq      # TODO: where is this even required?
        which skopeo  # TODO: where is this even required?

        echo "Docker tag will be: $DOCKER_TAG"  # TODO: add bundle sanity echo too
        make operator-sdk image release-build bundle bundle-build # bundle-push  # TODO: only push when build result is satisfying

# pseudo code steps
env vars to add/define:
