# TODO: when done remove ~/projects/jenkins-confs/jenkins-files/network-operator/ocp-bundle-push.jenkinsfile
name: Package OCP Bundle

on:
  push:  # TODO: consider appending this workflow/job into the network operator CI, since it depends on it (image must be pushed)
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:  # TODO: remove before merging
    - "feature/ocp-bundle"

jobs:
  package_ocp:
    runs-on: ubuntu-latest
    env:
      REGISTRY: nvcr.io/nvstaging/mellanox  # TODO: noam angel approved to change to nvstaging; requested we PoC it
      IMAGE_NAME: network-operator
      BUNDLE_IMAGE_NAME: network-operator-bundle
      GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      DOWNSTREAM_REPO_OWNER: nvidia-ci-cd
      UPSTREAM_REPO_OWNER: maze88  # TODO: revert to 'redhat-openshift-ecosystem' owner before merging
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Determine version and tag
      run: |
        git_tag=${{ github.ref_name }}
        echo VERSION_WITH_PREFIX=$git_tag        >> $GITHUB_ENV
        echo VERSION_WITHOUT_PREFIX=${git_tag:1} >> $GITHUB_ENV  # without the 'v' prefix
        echo VERSION_WITH_PREFIX=v99.9.9-beta.2   >> $GITHUB_ENV  # TODO: remove mock version - to be used only for development testing!
        echo VERSION_WITHOUT_PREFIX=99.9.9-beta.2 >> $GITHUB_ENV  # TODO: remove mock version - to be used only for development testing!
        git_tag=v24.4.0                                           # TODO: remove mock version after development
        network_operator_digest=$(skopeo inspect docker://$REGISTRY/$IMAGE_NAME:$git_tag | jq -r .Digest)
        echo $network_operator_digest | wc -w | grep 1  # verifies value not empty
        echo NETWORK_OPERATOR_DIGEST=$network_operator_digest >> $GITHUB_ENV
    - name: Make bundle
      id: make-bundle
      env:
        DEFAULT_CHANNEL: ${{ env.VERSION_WITH_PREFIX }}
        CHANNELS: stable,${{ env.VERSION_WITH_PREFIX }}
        TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ env.NETWORK_OPERATOR_DIGEST }}
        BUNDLE_IMG: ${{ env.REGISTRY }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}-mzeevi-test-deleteme  # TODO: remove "mzeevi-test-deleteme" suffix, after development
        VERSION: ${{ env.VERSION_WITHOUT_PREFIX }}
        NGC_CLI_API_KEY: ${{ secrets.NVCR_TOKEN }}
      run: |
        echo "Bundle's full tag will be: $BUNDLE_IMG"
        make bundle # bundle-build bundle-push  # TODO: uncomment last targets, after development  # TODO: confirm we can ommit `image` and `release-build` targets
    - name: Commit bundle to Network-Operator
      if: false  # TODO: temporarily disabled while developing pr to rh step; remove this conditional before merging
      env:
        DEFAULT_BRANCH: feature/ocp-bundle  # TODO: revert to `master` before merging
        FEATURE_BRANCH: feature/update-ocp-bundle-to-${{ env.VERSION_WITH_PREFIX }}
      run: |
        git config user.name  nvidia-ci-cd
        git config user.email svc-cloud-orch-gh@nvidia.com

        git fetch origin $DEFAULT_BRANCH
        git checkout $DEFAULT_BRANCH
        git checkout -b $FEATURE_BRANCH
        git add bundle
        git commit -sm "task: update bundle to $VERSION_WITH_PREFIX"

        git push -u origin $FEATURE_BRANCH
        gh pr create \
          --head $FEATURE_BRANCH \
          --base $DEFAULT_BRANCH \
          --fill \
          --body "Created by the *${{ github.job }}* job in [${{ github.repository }} OCP bundle CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
        gh pr merge --admin --merge $FEATURE_BRANCH  # requires repository settings to "allow auto-merge"
    - name: Determine if to send bundle to RedHat
      id: determine-if-to-send-bundle-to-redhat
      run: |
        echo SEND_BUNDLE_TO_REDHAT=$(echo ${{ github.ref_name}} | grep -E "v[0-9]+.[0-9]+.[0-9]+$" && echo true || echo false) >> $GITHUB_ENV
    - uses: actions/checkout@v4
      if: ${{ env.SEND_BUNDLE_TO_REDHAT }}
      with:
        token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
        # persist-credentials: true  # TODO: check if needed
        repository: ${{ env.UPSTREAM_REPO_OWNER }}/certified-operators
        path: certified-operators
    - name: Create PR with bundle to RedHat
      if: ${{ env.SEND_BUNDLE_TO_REDHAT }}
      env:
        DEFAULT_BRANCH: main
        FEATURE_BRANCH: nvidia/network-operator-bundle-${{ env.VERSION_WITHOUT_PREFIX }}
        NEW_BUNDLE_DIR: operators/nvidia-network-operator/${{ env.VERSION_WITHOUT_PREFIX }}
      run: |
        pushd certified-operators

        git config user.name  nvidia-ci-cd
        git config user.email svc-cloud-orch-gh@nvidia.com

        gh repo fork --remote --default-branch-only
        gh repo sync $DOWNSTREAM_REPO_OWNER/certified-operators --source $UPSTREAM_REPO_OWNER/certified-operators --branch $DEFAULT_BRANCH

        git checkout -b $FEATURE_BRANCH
        mkdir -p $NEW_BUNDLE_DIR
        cp -r ../bundle/* $NEW_BUNDLE_DIR
        git add $NEW_BUNDLE_DIR
        git commit -m "feat: add nvidia network operator bundle $VERSION_WITHOUT_PREFIX"

        git push -u origin $FEATURE_BRANCH
        gh pr create \
          --head $DOWNSTREAM_REPO_OWNER:$FEATURE_BRANCH \
          --base $DEFAULT_BRANCH \
          --title "operator nvidia-network-operator ($VERSION_WITHOUT_PREFIX)" \
          --body "Created by the *${{ github.job }}* job in [${{ github.repository }} OCP bundle CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
        popd
