# TODO: when done remove ~/projects/jenkins-confs/jenkins-files/network-operator/ocp-bundle-push.jenkinsfile
name: Package OCP Bundle

on:
  push:
    branches:
    - "feature/ocp-bundle"  # TODO: remove before merging
    - "master"
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"  # TODO: safe to remove wild card from end of pattern?

jobs:
  ocp-package:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: feature/ocp-bundle # master  # TODO: revert to 'master' when done
      REGISTRY: nvcr.io/nvstaging/mellanox
      IMAGE_NAME: network-operator
      # BUNDLE_REGISTRY: harbor.mellanox.com/cloud-orchestration-dev  # noam angel approved to change to nvstaging; requested we PoC it
      BUNDLE_IMAGE_NAME: network-operator-bundle
    steps:
    - uses: actions/checkout@v4
    - if: github.ref_name == env.DEFAULT_BRANCH
      name: Determine docker tag (when git branch)
      run: |
        echo VERSION_WITH_PREFIX=v0.0.0-$(git rev-parse --short HEAD) >> $GITHUB_ENV  # mock version - to be used only for internal testing!
        echo VERSION_WITHOUT_PREFIX=${VERSION_WITH_PREFIX:1}          >> $GITHUB_ENV
    - if: github.ref_type == 'tag'
      name: Determine docker tag (when git tag)
      run: |
        git_tag=${{ github.ref_name }}
        echo VERSION_WITH_PREFIX=$git_tag        >> $GITHUB_ENV
        echo VERSION_WITHOUT_PREFIX=${git_tag:1} >> $GITHUB_ENV  # without the 'v' prefix
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Make bundle
      env:
        TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}
        BUNDLE_IMG: ${{ env.REGISTRY }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.VERSION_WITH_PREFIX }}
        DEFAULT_CHANNEL: stable
        CHANNELS: stable,${{ env.VERSION_WITH_PREFIX }}
        VERSION: ${{ env.VERSION_WITHOUT_PREFIX }}
      run: |
        echo "Bundle tag will be: $BUNDLE_IMG"
        # make image release-build bundle bundle-build # bundle-push  # TODO: only push when build result is satisfying
        # TODO: revert fine-grain separate make targets (instead of line above), after troubleshooting
        echo 'DEBUG AAAAA'
        make image
        echo 'DEBUG BBBBB'
        make release-build
        echo 'DEBUG CCCCC'
        make bundle  # TODO: troubleshoot this command: https://github.com/maze88/network-operator/actions/runs/9566948719/job/26373450337#step:6:1170
        echo 'DEBUG DDDDD'
        make bundle-build
